### ISSUE TITLE
zambujo's RopenSci Review

### ISSUE THREAD

**Issue by adam3smith** [PESData/awardFindR#25]
https://github.com/ropensci/software-review/issues/432#issuecomment-851939864

Definitely do:

- [x] Use Roxygen inherit functionality for documentation
- [x] Move installation instructions toward top of readme (I'd say right after the initial paragraph) + add heading for supported sites and maybe move those down?
- [x] Check on use of `read_csv` and `readr`

Discuss

- [x] Change main function name to not clash w package name (I'd be inclined to to this)
- [x] Change verb/subject order of function from `neh_get` to `get_neh`. Check whether this is indeed more common. Practically, upside for using `neh` first is quicker auto-complete. Upside of using `get_` first is that you see all `get_` functions as part of autocomplete. I could go either way here. Can also ask on Twitter.

**Comment by mccallc** [comment]
I was personally more inclined to the autocomplete argument for `neh_get` rather than `get_neh` format, but it looks like the verb_subject format is more common in rOpenSci projects. Examples:

https://docs.ropensci.org/FedData/reference/index.html
https://docs.ropensci.org/c14bazAAR/reference/index.html

I'll change the function names to reflect this trend.

Also: changed the main function name from `awardFindR` to `award_search` as a trial balloon to see what bugs would pop up. If we're going for this format, though, I assume we want something more like `search_awards`?

**Comment by adam3smith** [comment]
> I'll change the function names to reflect this trend.
Yeah, that makes sense then.

> Also: changed the main function name from awardFindR to award_search as a trial balloon to see what bugs would pop up. If we're going for this format, though, I assume we want something more like search_awards?

Yes, let's do verb_noun throughout then
