### ISSUE TITLE
error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by wsphd** [PESData/awardFindR#26]
I changed the keyword argument from "ethnography" in my example to "data" (and even more specifically "data science" (e.g., awardFindR::search_awards(keywords="data")) and I get the following error:

                                                                            
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In request(url, "post", verbose, payload) : Bad Request (HTTP 400).

**Comment by mccallc** [comment]
Thanks for the report. 

I recreated this error, and it looks like it's the same issue as #20, when a search is so broad that it pulls in over 10,000 NIH awards. This is a limitation of the NIH RePORTER API.

I'm currently testing out a new NIH search strategy that will hopefully improve specificity for searches like "data science". Because the 10,000 limit comes from the API, though, a search as generic as "data" may be difficult to make work without narrow date parameters

**Comment by mccallc** [comment]
Partially fixed in commit f688af5d620903b2837e097a69fb44fd1ad58ddb
